# -*- coding: utf-8 -*-
"""task3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-WWwADQHK-LnQxHagA5yWloHRxJ1EbmX
"""

import random

# The text my "AI" will read and learn from
training_text = """
the cat sat on the mat and the dog sat on the rug
the cat chased the mouse and the dog chased the cat
"""

# Split the text into individual words
words = training_text.split()

# Create a memory dictionary (database)
word_memory = {}

# Teach the AI by learning word transitions
for i in range(len(words) - 1):
    current_word = words[i]
    next_word = words[i + 1]

    # Create empty list if word not seen before
    if current_word not in word_memory:
        word_memory[current_word] = []

    # Store next word
    word_memory[current_word].append(next_word)

# Display learned memory
print("--- AI Memory Check ---")
print("Words that can follow 'the':", word_memory['the'])
print("Words that can follow 'sat':", word_memory['sat'])
print()

# Generate new text
print("--- Generated Text ---")

# Start from a random word
current = random.choice(words)

generated_story = [current]

# Generate 15 words
for _ in range(15):

    # Check if current word exists in memory
    if current in word_memory:

        # Pick a random next word
        next_word = random.choice(word_memory[current])

        # Add to story
        generated_story.append(next_word)

        # Move forward
        current = next_word
    else:
        break

# Print final generated text
print(" ".join(generated_story))

